### ISSUE TITLE
Error Handling after successful form submission

### ISSUE THREAD

**Issue by mdwiltfong** [cecmahumane/ecommerce-api-using-tdd#1]
It was noticed that when the database wasn't connected, the registration form behaved in the same manner as if there was a successful registration. 

Better error handling will be needed to handle errors AFTER successful form submission, whether it's a 500 internal server error, or some other error code.

**Comment by cecmahumane** [comment]
I think I've resolved this.  
![image](https://user-images.githubusercontent.com/83076432/188501121-d986b69d-a153-483d-adaf-04eb2697f366.png)

These are the error messages returned when my database pool is commented out, essentially disconnecting it. 
The GET requests apply to the front-end fetching images (newly added) on render of the home page, and the POST requests that fail were a result of manual testing of the registration button when all fields are correctly filled once the database was disconnected.

Please let me know if this is sufficient.
