### ISSUE TITLE
@cecmahumaine look into the proper use of REACT enviornment variables so that this route works dynamically */

### ISSUE THREAD

**Issue by mdwiltfong** [cecmahumane/ecommerce-api-using-tdd#12]
```
      /* TODO: @cecmahumaine look into the proper use of REACT enviornment variables so that this route works dynamically */
```

https://github.com/mdwiltfong/ecommerce-api-using-tdd/blob/76eb4cd904b129de8655ff4830ff17d8da85acae/src/components/ProductBox.js#L15

**Comment by cecmahumane** [comment]
I described where to place .env file and variables in my documentation according to this:
https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env

Please let me know of I need to adjust anything.
