### ISSUE TITLE
Create a .env.example and reference it in your readme

### ISSUE THREAD

**Issue by mdwiltfong** [cecmahumane/ecommerce-api-using-tdd#13]
In order to create a better developer experience, it's recommended to create a .env.example that will guide users on how to connect to their local DB through your application

**Comment by cecmahumane** [comment]
Hmmm... did you mean to put that .env.example in my repository within my app? I added instructions to my documentation surrounding .env files and startup information. Please let me know if this is sufficient or if there is a better way to do this.

**Comment by mdwiltfong** [comment]
We addressed this in person during the weekly chapter meetings, and this issue was solved in [this PR](https://github.com/cecmahumane/ecommerce-api-using-tdd/pull/8)
