### ISSUE TITLE
Resolving req.session issue

### ISSUE THREAD

**Issue by cecmahumane** [cecmahumane/ecommerce-api-using-tdd#14]
Help find out where the problem lies in the assignment of the cookie to the client.

**Comment by mdwiltfong** [comment]
I'd love to pick this up! If you'd be so kind to assign it to me that would be great!

**Comment by mdwiltfong** [comment]
This was resolved in this [PR](https://github.com/cecmahumane/ecommerce-api-using-tdd/pull/15)

**Comment by cecmahumane** [comment]
Issue resolved.
