### ISSUE TITLE
Stripe Integration 

### ISSUE THREAD

**Issue by mdwiltfong** [cecmahumane/ecommerce-api-using-tdd#19]
Part of the final project in Codecademy is to add a Stripe Integration to the app to process orders.

**Comment by mdwiltfong** [comment]
One question is whether the app should save the client's payment information for later use, specifically if they log into the app. How would this be achievable through Stripe?

**Comment by mdwiltfong** [comment]
Looking into Stripe's docs, it looks like this will involve some duplication. Mainly duplicating customers between the storefront and  Stripe's database. Additional information can be found [here](https://stripe.com/docs/checkout/quickstart?lang=node&client=react).

**Comment by cecmahumane** [comment]
Stripe integrated successfully.
