### ISSUE TITLE
Registration Will Always Return an HTTP Status of 500 

### ISSUE THREAD

**Issue by mdwiltfong** [cecmahumane/ecommerce-api-using-tdd#3]
In the event a user fails registration, the API will always return an HTTP Status code 0f 500. This might not always be accurate.

**Comment by cecmahumane** [comment]
Inserted a 409(conflict) error for when duplicate emails are detected by the database during the POST request in profile.js.

![image](https://user-images.githubusercontent.com/83076432/187740503-178ffaa5-ff5c-4dea-b9ed-ae33d715fba2.png)

**Comment by mdwiltfong** [comment]
@cecmahumane That's awesome! Now your server can handle that scenario! 

I'm wondering though if there is a way to handle the error message and status code more dynamically.Let me look at my notes and your recents commits and get back to you.
