### ISSUE TITLE
Cypress Page Object Model

### ISSUE THREAD

**Issue by mdwiltfong** [cecmahumane/ecommerce-api-using-tdd#6]
In order to create a scalable test suite, the cypress test should follow the Page Object Model.

**Comment by mdwiltfong** [comment]
@cecmahumane , would you be so kind as to assign this issue to me? That way, my PRs and activities can be documented here.

**Comment by mdwiltfong** [comment]
The PR needs more work, but I've gone ahead and layed the foundation out for the Page Object Model for the registration page and the login page. The tests need to be updated, so it's not ready for review or to be merged.

**Comment by mdwiltfong** [comment]
I've broken the original test "User can navigate to registration page from LoginPage and register" into two tests:
- "User can navigate to registration page from loginPage"
- "User can register on registration page"
Although, the test is limited because i'm not sure what the expected behavior will be upon successful registration and unsuccessful registration. 

@cecmahumane , we can maybe meet up next week on wednesday to talk more about it, or if you can describe the happy path I can maybe write something up from that description. [Here's](https://github.com/cecmahumane/ecommerce-api-using-tdd/pull/8/commits/f8be0ab77a80923b87d49dccfc7ca474bb44733b) my latest addition.

**Comment by cecmahumane** [comment]
@mdwiltfong I'd be happy to meet and discuss it if you are holding a session tonight ( Wednesday 31, 2022).

**Comment by mdwiltfong** [comment]
@cecmahumane Unfortunately we're not meeting tonight, but let's keep up the momentum and work on this asynchronously. 

I'll just work with testids. So regardless of how you handle the successful registration or failure, we can agree that in either case you'll probably use a data-testId of `successful-registration` or `failed-registration`

That way I can finish up this PR and set you up for happy testing!

**Comment by cecmahumane** [comment]
Thanks I really appreciate your time. 

Yes, I was just about re-read that article on the page object model. 

Regarding the testids, should I add these data-testids to my project in the register.cy.js file? Also Should I add some success indicator on the login page with  the  `successful-registration` data-testid or one for failure? Is that what your suggesting?

**Comment by mdwiltfong** [comment]
I was suggesting the latter. So as long as you plan to use a `data-test` tag, similar to what you did [here](https://github.com/cecmahumane/ecommerce-api-using-tdd/blob/d651a7339c331841d58dc3e2c6f8566c0e7ae1a5/src/components/Login.js#L7) the tests I'll write will probably be good.
